typing_speed_trainer/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('social/', include('social_django.urls', namespace='social')),
    path('', include('trainer.urls')),
    path('trainer/api/', include('trainer_api.urls')),
    path('account/', include('account.urls')),
    path('auth/', include('user_auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

typing_speed_trainer/user_auth/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from user_auth import views


app_name = 'user_auth'

urlpatterns = [
    path('login/', views.UserLogin.as_view(), name='login'),
    path('registration/', views.UserRegistration.as_view(), name='registration'),

    path('reset_password/', views.UserPasswordReset.as_view(), name='reset_password'),
    path('reset/<uidb64>/<token>/', views.UserPasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('logout/', LogoutView.as_view(), name='logout')
]

typing_speed_trainer/user_auth/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm, SetPasswordForm

from account.models import User
from common.form_mixins import CrispyStyleModelFormMixin, CrispyStyleFormMixin


class RegistrationForm(CrispyStyleModelFormMixin):
    """The registration form."""

    repeat_password = forms.CharField(label="Повторите пароль", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email', 'username', 'password', 'repeat_password']

        error_messages = {
            'email': {
                'unique': "Пользователь с такой почтой уже существует.",
            },
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].help_text = None

    def clean_repeat_password(self):
        """Checks if passwords match each other."""
        if self.cleaned_data['repeat_password'] != self.cleaned_data['password']:
            raise forms.ValidationError("Пароли не совпадают")
        return self.cleaned_data['repeat_password']

    def save(self, commit=True):
        instance: User = super().save(commit=False)
        instance.set_password(instance.password)
        instance.save()
        return instance


class LoginForm(AuthenticationForm, CrispyStyleFormMixin):
    """The authentication form."""

    username = forms.EmailField(label="Почта")

    error_messages = {
        "invalid_login": "Введите правильную почту и пароль.",
        "inactive": "Этот аккаунт неактивен.",
    }


class UserPasswordResetForm(PasswordResetForm, CrispyStyleFormMixin):
    """
    Форма сброса пароля. Для восстановления пароля использует
    почту пользователя.
    """


class UserPasswordResetConfirmForm(SetPasswordForm, CrispyStyleFormMixin):
    """
    Форма для изменения пароля. Для восстановления пароля использует
    почту пользователя.
    """

    new_password1 = forms.CharField(
        label="Новый пароль",
        widget=forms.PasswordInput(),
        strip=False,
    )

typing_speed_trainer/user_auth/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetConfirmView
from django.urls import reverse_lazy
from django.views.generic import CreateView

from user_auth.forms import RegistrationForm, LoginForm, UserPasswordResetForm, UserPasswordResetConfirmForm
from common.mixins import UnauthenticatedMixin


class UserRegistration(CreateView, UnauthenticatedMixin):
    """The register page."""

    template_name = 'user_auth/registration.html'
    form_class = RegistrationForm

    def form_valid(self, form):
        response = super().form_valid(form)
        login(self.request, self.object, backend='account.backends.EmailBackend')
        return response


class UserLogin(LoginView):
    """The authentication page."""

    form_class = LoginForm
    template_name = 'user_auth/login.html'
    redirect_authenticated_user = True


class UserPasswordReset(PasswordResetView, UnauthenticatedMixin):
    """The page for user's password recovery."""

    form_class = UserPasswordResetForm
    success_url = reverse_lazy('user_auth:login')
    email_template_name = 'user_auth/password_reset_email.html'
    template_name = 'user_auth/user_password_reset_form.html'

    def form_valid(self, form):
        messages.success(self.request, "Письмо было отправлено")
        return super().form_valid(form)


class UserPasswordResetConfirm(PasswordResetConfirmView, UnauthenticatedMixin):
    """
    The page for the password change. It is used via special link
    that is sent on user's email.
    """

    form_class = UserPasswordResetConfirmForm
    template_name = 'user_auth/user_password_reset_confirm.html'
    success_url = reverse_lazy('user_auth:login')

    def form_valid(self, form):
        messages.success(self.request, "Пароль был успешно изменён")
        return super().form_valid(form)

typing_speed_trainer/user_auth/templates/user_auth/auth_base.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'user_auth/css/auth-base-style.css' %}">
{% endblock %}

{% block content %}
<div class="container mt-5">

    <div class="row justify-content-center align-items-center">
        <div class="col-4">
            <div class="d-flex flex-column">

                {% include 'includes/alerts.html' %}

                {% block alert %}

                {% endblock %}

            </div>
        </div>
    </div>

    <div class="row justify-content-center align-items-center">
        <div class="col-4">
            <div class="p-4 bg-blue-800 rounded text-light">

                <div class="d-flex justify-content-center align-items-center pb-2 border-blue-200-bottom">
                    <span class="fs-4 fw-light">Typing practise</span>
                </div>

                {% block auth_content %}

                {% endblock %}

                <div class="d-flex flex-column mt-5">
                    {% block add_link %}

                    {% endblock %}
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}

typing_speed_trainer/user_auth/templates/user_auth/login.html
{% extends 'user_auth/auth_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block stylesheet %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'user_auth/css/login-page.css' %}">
{% endblock %}

{% block alert %}
{% if form.non_field_errors %}
<div class="alert alert-danger">
    {% for error in form.non_field_errors %}
    <span>{{ error }}</span>
    {% endfor %}
</div>
{% endif %}
{% endblock %}

{% block auth_content %}
<div class="d-flex justify-content-center align-items-center mt-2 mb-3">
    <span class="fs-5 fw-light">Вход</span>
</div>

<form action="{% url 'user_auth:login' %}" method="post" novalidate>
    <div class="d-flex flex-column">

        {% crispy form %}

        <div class="d-flex justify-content-center mt-2">
            <button type="submit" class="btn-orange-400">Войти</button>
            <div class="d-flex justify-content-center align-items-center ms-2">
                <a class="btn-main-800 rounded text-light shadow-sm" href="{% url 'social:begin' 'github' %}">
                    <i class="bi bi-github"></i>
                </a>
            </div>
        </div>

    </div>
</form>
{% endblock %}

{% block add_link %}
<a href="{% url 'user_auth:registration' %}">Создать аккаунт</a>
<a href="{% url 'user_auth:reset_password' %}">Забыли пароль</a>
{% endblock %}

typing_speed_trainer/user_auth/templates/user_auth/password_reset_email.html
Чтоб изменить пароль, перейдите по ссылке ниже:
{{ protocol }}://{{ domain }}{% url "user_auth:password_reset_confirm" uidb64=uid token=token %}
Если вы не хотели менять пароль и вам пришло это письмо, то просто проигнорируйте его.

typing_speed_trainer/user_auth/templates/user_auth/registration.html
{% extends 'user_auth/auth_base.html' %}
{% load crispy_forms_tags %}

{% block auth_content %}
<div class="d-flex justify-content-center align-items-center mt-2 mb-3">
    <span class="fs-5 fw-light">Регистрация</span>
</div>

<form action="{% url 'user_auth:registration' %}" method="post" novalidate>
    <div class="d-flex flex-column">
        {% crispy form %}
        <div class="d-flex justify-content-center mt-2">
            <button type="submit" class="btn-orange-400">Зарегистрироваться</button>
        </div>
    </div>
</form>
{% endblock %}

{% block add_link %}
<a href="{% url 'user_auth:login' %}">Уже есть аккаунт?</a>
{% endblock %}

typing_speed_trainer/user_auth/templates/user_auth/user_password_reset_confirm.html
{% extends 'user_auth/auth_base.html' %}
{% load crispy_forms_tags %}

{% block auth_content %}
<div class="d-flex justify-content-center align-items-center mt-2 mb-3">
    <span class="fs-5 fw-light">Смена пароля</span>
</div>

<form action="." method="post" novalidate>
    <div class="d-flex flex-column">
        {% crispy form %}
        <div class="d-flex justify-content-center mt-2">
            <button type="submit" class="btn-orange-400">Сменить пароль</button>
        </div>
    </div>
</form>
{% endblock %}

{% block add_link %}
<a href="{% url 'user_auth:login' %}">Войти</a>
{% endblock %}

typing_speed_trainer/user_auth/templates/user_auth/user_password_reset_form.html
{% extends 'user_auth/auth_base.html' %}
{% load crispy_forms_tags %}

{% block alert %}
{% if form.non_field_errors %}
<div class="alert alert-danger">
    {% for error in form.non_field_errors %}
    <span>{{ error }}</span>
    {% endfor %}
</div>
{% endif %}
{% endblock %}

{% block auth_content %}
<div class="d-flex justify-content-center align-items-center mt-2 mb-3">
    <span class="fs-5 fw-light">Сброс пароля</span>
</div>

<div class="mb-4">
    <p class="lh-sm m-0">
        <small>Введите свою почту, на которую мы отправим ссылку для сброса пароля.</small>
    </p>
</div>

<form action="{% url 'user_auth:reset_password' %}" method="post" novalidate>
    <div class="d-flex flex-column">
        {% crispy form %}
        <div class="d-flex justify-content-center mt-2">
            <button type="submit" class="btn-orange-400">Отправить</button>
        </div>
    </div>
</form>
{% endblock %}

{% block add_link %}
<a href="{% url 'user_auth:registration' %}">Создать аккаунт</a>
<a href="{% url 'user_auth:login' %}">Войти</a>
{% endblock %}