typing_speed_trainer/account/urls.py
from django.urls import path

from account import views

app_name = 'account'

urlpatterns = [
    path('list/', views.UsersList.as_view(), name='users'),
    path('<int:pk>/', views.Account.as_view(), name='profile'),
    path('delete/photo/', views.DeleteProfilePhoto.as_view(), name='delete_profile_photo'),
    path('update/photo/', views.UpdateProfilePhoto.as_view(), name='update_profile_photo'),
    path('update/settings/', views.UpdateProfileSettings.as_view(), name='update_profile_settings'),
]

typing_speed_trainer/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('social/', include('social_django.urls', namespace='social')),
    path('', include('trainer.urls')),
    path('trainer/api/', include('trainer_api.urls')),
    path('account/', include('account.urls')),
    path('auth/', include('user_auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

typing_speed_trainer/trainer/urls.py
from django.urls import path
from trainer import views


app_name = 'trainer'

urlpatterns = [
    path('', views.TypingTrainer.as_view(), name='typing_trainer'),
]

typing_speed_trainer/user_auth/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from user_auth import views


app_name = 'user_auth'

urlpatterns = [
    path('login/', views.UserLogin.as_view(), name='login'),
    path('registration/', views.UserRegistration.as_view(), name='registration'),

    path('reset_password/', views.UserPasswordReset.as_view(), name='reset_password'),
    path('reset/<uidb64>/<token>/', views.UserPasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('logout/', LogoutView.as_view(), name='logout')
]

typing_speed_trainer/templates/includes/alerts.html
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}">
    {{ message }}
</div>
{% endfor %}
{% endif %}

typing_speed_trainer/templates/includes/footer.html
<footer class="bg-blue-800">
    <div class="container">
        <div class="py-4">
            <div class="d-flex flex-column text-light fw-bold">
                <small>Typing practise - 2022</small>
                <small><a href="https://github.com/BorisPlaton/typing_speed_trainer">Github</a></small>
            </div>
        </div>
    </div>
</footer>

typing_speed_trainer/templates/includes/header.html
<header>

    <div class="text-light bg-blue-800 py-3">
        <div class="container">
            <div class="logo">
                <a href="{% url 'trainer:typing_trainer' %}" class="link-light">
                    <span class="fs-4 fw-light"><i class="bi bi-chevron-right"></i>... Typing practise</span>
                </a>
            </div>
        </div>
    </div>

    <div class="bg-blue-500 border-blue-200-top border-blue-200-bottom fw-bold">

        <div class="container">
            <div class="py-1">
                <div class="row g-lg-5 g-4">

                    <div class="col-auto">
                        <a href="{% url 'trainer:typing_trainer' %}" class="link-light">Тренажер</a>
                    </div>

                    <div class="col-auto">
                        <a href="{% url 'account:users' %}" class="link-light">Другие люди</a>
                    </div>

                    {% if user.is_authenticated %}
                    <div class="col-auto">
                        <a href="{{ user.get_absolute_url }}" class="link-light">Мой профиль</a>
                    </div>

                    <div class="col-auto">
                        <a href="{% url 'user_auth:logout' %}" class="link-light">Выйти</a>
                    </div>
                    {% else %}
                    <div class="col-auto">
                        <a href="{% url 'user_auth:login' %}" class="link-light">Войти</a>
                    </div>
                    {% endif %}

                </div>
            </div>
        </div>

    </div>

</header>